MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '**'
  METRIC_LOSS_TYPE: 'triplet_center'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'yes'
  NAME: 'efficientnet-b7'
  DEVICE_ID: ('2')
  ID_LOSS_TYPE: 'arcface'
  ID_LOSS_WEIGHT: 0.1
  TRIPLET_LOSS_WEIGHT: 0.9
  WEIGHTED_TRIPLET: True
  NO_MARGIN: True

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATASETS:
  NAMES: ('naic')
  ROOT_DIR: ('/raid/chenby/person_rID')
  HARD_AUG: True
  ADD_2019: True

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Ranger'
  START_EPOCHS: 0
  MAX_EPOCHS: 50
  BASE_LR: 0.006
  IMS_PER_BATCH: 64
  STEPS: [25, 40]
  GAMMA: 0.1
  WARMUP_FACTOR: 0.01
  WARMUP_EPOCHS: 10
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 50
  EVAL_PERIOD: 10000
  COSINE_MARGIN: 0.4
  COSINE_SCALE: 30
  CENTER_LOSS_WEIGHT: 0.0003
  FP16: False

TEST:
  IMS_PER_BATCH: 128
  RE_RANKING: True
  WEIGHT: '/data1/cby/py_project/NAIC_Person_ReID_DMT/output/efn-b7_add-2019/efficientnet-b7_45_acc0.6045.pth'
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'
  FLIP_FEATS: 'on'
OUTPUT_DIR: "output/efn-b7_add-2019/"


